import os

DEBUG_CONSOLE_OUTPUT = False
ARDUINO_PORT = "/dev/ttyUSB0"
ARDUINO_BAUDRATE = 115200
ARDUINO_TIMEOUT = 5
TRAY_TOOLTIP = "LED strip control"
TRAY_ICON = os.path.dirname(__file__) + "/tray-icon.png"

CURRENT_COLOR = [255, 255, 255]
CURRENT_MODE = 0
CURRENT_BRIGHTNESS = 255
CURRENT_SPEED = 1000


class Modes:
    # grep 'FX_MODE_' WS2812FX.h | awk '{print $2,"=", $3}'
    FX_MODE_STATIC = 0
    FX_MODE_BLINK = 1
    FX_MODE_BREATH = 2
    FX_MODE_COLOR_WIPE = 3
    FX_MODE_COLOR_WIPE_INV = 4
    FX_MODE_COLOR_WIPE_REV = 5
    FX_MODE_COLOR_WIPE_REV_INV = 6
    FX_MODE_COLOR_WIPE_RANDOM = 7
    FX_MODE_RANDOM_COLOR = 8
    FX_MODE_SINGLE_DYNAMIC = 9
    FX_MODE_MULTI_DYNAMIC = 10
    FX_MODE_RAINBOW = 11
    FX_MODE_RAINBOW_CYCLE = 12
    FX_MODE_SCAN = 13
    FX_MODE_DUAL_SCAN = 14
    FX_MODE_FADE = 15
    FX_MODE_THEATER_CHASE = 16
    FX_MODE_THEATER_CHASE_RAINBOW = 17
    FX_MODE_RUNNING_LIGHTS = 18
    FX_MODE_TWINKLE = 19
    FX_MODE_TWINKLE_RANDOM = 20
    FX_MODE_TWINKLE_FADE = 21
    FX_MODE_TWINKLE_FADE_RANDOM = 22
    FX_MODE_SPARKLE = 23
    FX_MODE_FLASH_SPARKLE = 24
    FX_MODE_HYPER_SPARKLE = 25
    FX_MODE_STROBE = 26
    FX_MODE_STROBE_RAINBOW = 27
    FX_MODE_MULTI_STROBE = 28
    FX_MODE_BLINK_RAINBOW = 29
    FX_MODE_CHASE_WHITE = 30
    FX_MODE_CHASE_COLOR = 31
    FX_MODE_CHASE_RANDOM = 32
    FX_MODE_CHASE_RAINBOW = 33
    FX_MODE_CHASE_FLASH = 34
    FX_MODE_CHASE_FLASH_RANDOM = 35
    FX_MODE_CHASE_RAINBOW_WHITE = 36
    FX_MODE_CHASE_BLACKOUT = 37
    FX_MODE_CHASE_BLACKOUT_RAINBOW = 38
    FX_MODE_COLOR_SWEEP_RANDOM = 39
    FX_MODE_RUNNING_COLOR = 40
    FX_MODE_RUNNING_RED_BLUE = 41
    FX_MODE_RUNNING_RANDOM = 42
    FX_MODE_LARSON_SCANNER = 43
    FX_MODE_COMET = 44
    FX_MODE_FIREWORKS = 45
    FX_MODE_FIREWORKS_RANDOM = 46
    FX_MODE_MERRY_CHRISTMAS = 47
    FX_MODE_FIRE_FLICKER = 48
    FX_MODE_FIRE_FLICKER_SOFT = 49
    FX_MODE_FIRE_FLICKER_INTENSE = 50
    FX_MODE_CIRCUS_COMBUSTUS = 51
    FX_MODE_HALLOWEEN = 52
    FX_MODE_BICOLOR_CHASE = 53
    FX_MODE_TRICOLOR_CHASE = 54
    FX_MODE_CUSTOM = 55
    FX_MODE_CUSTOM_0 = 55
    FX_MODE_CUSTOM_1 = 56
    FX_MODE_CUSTOM_2 = 57
    FX_MODE_CUSTOM_3 = 58
    FX_MODE_CUSTOM_4 = 59
    FX_MODE_CUSTOM_5 = 60
    FX_MODE_CUSTOM_6 = 61
    FX_MODE_CUSTOM_7 = 62

    @classmethod
    def get_all_const(cls):
        modes = {}
        for name in dir(cls):
            if name.startswith("FX_MODE_"):
                modes[name] = getattr(cls, name)
        # sort by value (id)
        return {k: v for k, v in sorted(modes.items(), key=lambda item: item[1])}
